# Site settings
baseurl = "//sclif.pro/"
# HTML Language Code Reference, such as en, zh-cn
languageCode = "ru-ru"
publishDir = "docs"
title = "ИТ заметки"
theme = "hugo-theme-cactus-plus"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-30560332-1"

[params]
	name = "Sclif.pro"
	description = "ИТ заметки"
	bio = "ИТ заметки"
	# Enter optionally your twitter account
	# twitter = "your_twotter"
	enableRSS = false

	# Disqus comment
	disqusShortname = "sclif-pro"
	# Disable disqus comments by set `enableDisqus = "false"`
	enableDisqus = false

	enableGithubIssuesTips = false

	# Use description as title in single page, posts page and tags page.
	useDescriptionAsTitle = false

	# Enable googleAnalytics
	enableGoogleAnalytics = true

	# Enable baiduAnalytics
	enableBaiduAnalytics = false
	# Baidu Tongji Code
	baiduAnalytics = 'your_baidu_tongji_code'

	# Add custom assets with their paths relative to the static folder
	customCSS = ["/css/img.css"]
	customJS  = ["/js/redirect.js"]

	# The variables below are optionally too and can be used to
	# translate or customize each string of the theme.

	# Navigation links
	home = ""
	about = ""
	archive = ""
	subscribe = ""
	projects = ""
	# Pagination links
	olderPosts = ""
	newerPosts = ""
	readMore = " "
	copyright = ""
	# Sharing options and author information in posts
	aboutAuthor = ""
	tweet = ""
	share = ""
	# 404 page
	title404 = "Кажется что-то случилось"
	subtitle404 = "страница не найдена"

	# Choose a font for the social icons in the footer. Either "mono-social" or "font-awesome"
	iconFont = "font-awesome"
    # The social icons can be styled differently if you use mono as font - circle, rounded, or empty
    socialIconStyle = ""


# Add additional social link entries underneath
[social]
    github-square = "https://github.com/sclif13"
	instagram = "https://www.instagram.com/sclif13/"